// 标准版和专业版题库扩展
// quick 版题库在各自模块文件中已定义，此处补充 standard 和 pro 版

import type { QuizQuestion } from "../quiz-types";

// ═══════════════════════════════════════════════════════
// 大五人格 — standard(25题) + pro(50题)
// ═══════════════════════════════════════════════════════
export const BIG_FIVE_STANDARD: QuizQuestion[] = [
  { id:"bf_s01",dimension:"openness",text:"我喜欢尝试不同风格的音乐、电影或艺术形式。",reverse:false},
  { id:"bf_s02",dimension:"openness",text:"我对抽象概念和理论探讨有兴趣。",reverse:false},
  { id:"bf_s03",dimension:"openness",text:"我更喜欢按既定方式做事，而不是尝试新方法。",reverse:true},
  { id:"bf_s04",dimension:"openness",text:"旅行或去没去过的地方让我感到兴奋。",reverse:false},
  { id:"bf_s05",dimension:"openness",text:"我觉得传统和惯例比创新更重要。",reverse:true},
  { id:"bf_s06",dimension:"conscientiousness",text:"我会把需要做的事列成清单。",reverse:false},
  { id:"bf_s07",dimension:"conscientiousness",text:"别人可以依赖我来完成我承诺的事。",reverse:false},
  { id:"bf_s08",dimension:"conscientiousness",text:"我有时会因为分心而忘记把事做完。",reverse:true},
  { id:"bf_s09",dimension:"conscientiousness",text:"我喜欢把工作空间整理得井井有条。",reverse:false},
  { id:"bf_s10",dimension:"conscientiousness",text:"面对大任务，我常常不知从哪开始。",reverse:true},
  { id:"bf_s11",dimension:"extraversion",text:"在聚会上我通常是主动和人聊天的那类人。",reverse:false},
  { id:"bf_s12",dimension:"extraversion",text:"我喜欢成为注意力的中心。",reverse:false},
  { id:"bf_s13",dimension:"extraversion",text:"我更喜欢一个人安静待着而不是去热闹场合。",reverse:true},
  { id:"bf_s14",dimension:"extraversion",text:"和陌生人交谈对我来说不算难事。",reverse:false},
  { id:"bf_s15",dimension:"extraversion",text:"人多的时候我往往选择沉默而不是主动发言。",reverse:true},
  { id:"bf_s16",dimension:"agreeableness",text:"我通常相信别人是善意的。",reverse:false},
  { id:"bf_s17",dimension:"agreeableness",text:"当别人遇到困难时,我会主动提供帮助。",reverse:false},
  { id:"bf_s18",dimension:"agreeableness",text:"如果我觉得对方不对，我会直接指出来，不太顾及语气。",reverse:true},
  { id:"bf_s19",dimension:"agreeableness",text:"我善于从别人的角度理解问题。",reverse:false},
  { id:"bf_s20",dimension:"agreeableness",text:"比起合作，我更喜欢独立完成任务。",reverse:true},
  { id:"bf_s21",dimension:"neuroticism",text:"小事也能让我紧张好一阵子。",reverse:false},
  { id:"bf_s22",dimension:"neuroticism",text:"我经常担心事情会出问题。",reverse:false},
  { id:"bf_s23",dimension:"neuroticism",text:"我的情绪大部分时候都比较稳定。",reverse:true},
  { id:"bf_s24",dimension:"neuroticism",text:"遭批评后我需要比较长的时间才能缓过来。",reverse:false},
  { id:"bf_s25",dimension:"neuroticism",text:"我很少因为压力而感到不堪重负。",reverse:true},
];

export const BIG_FIVE_PRO: QuizQuestion[] = [
  ...BIG_FIVE_STANDARD,
  { id:"bf_p01",dimension:"openness",text:"我喜欢花时间思考哲学或抽象问题。",reverse:false},
  { id:"bf_p02",dimension:"openness",text:"我愿意改变已有的观点当新证据出现时。",reverse:false},
  { id:"bf_p03",dimension:"openness",text:"我不太关心艺术或美学方面的东西。",reverse:true},
  { id:"bf_p04",dimension:"openness",text:"我喜欢学习新技能，即使和我的主业无关。",reverse:false},
  { id:"bf_p05",dimension:"openness",text:"我认为按部就班比天马行空更靠谱。",reverse:true},
  { id:"bf_p06",dimension:"conscientiousness",text:"我在开始一项任务前会花时间充分准备。",reverse:false},
  { id:"bf_p07",dimension:"conscientiousness",text:"即使没有人检查我也会按标准完成工作。",reverse:false},
  { id:"bf_p08",dimension:"conscientiousness",text:"我习惯把事情拖到最后一刻。",reverse:true},
  { id:"bf_p09",dimension:"conscientiousness",text:"我注重细节，不喜欢粗枝大叶。",reverse:false},
  { id:"bf_p10",dimension:"conscientiousness",text:"我经常忘记把东西放回原位。",reverse:true},
  { id:"bf_p11",dimension:"extraversion",text:"我享受快节奏、充满活力的环境。",reverse:false},
  { id:"bf_p12",dimension:"extraversion",text:"我通常能和刚认识的人很快找到话题。",reverse:false},
  { id:"bf_p13",dimension:"extraversion",text:"连续社交几小时后我只想一个人待着。",reverse:true},
  { id:"bf_p14",dimension:"extraversion",text:"在团队中我通常是活跃气氛的那个人。",reverse:false},
  { id:"bf_p15",dimension:"extraversion",text:"我更倾向用文字而非当面交流来表达复杂想法。",reverse:true},
  { id:"bf_p16",dimension:"agreeableness",text:"即使和我不喜欢的人共事，我也能保持合作态度。",reverse:false},
  { id:"bf_p17",dimension:"agreeableness",text:"我很难对别人的请求说不。",reverse:false},
  { id:"bf_p18",dimension:"agreeableness",text:"对于我认为不合理的规则，我会公开质疑。",reverse:true},
  { id:"bf_p19",dimension:"agreeableness",text:"我宁愿让步也不想让冲突升级。",reverse:false},
  { id:"bf_p20",dimension:"agreeableness",text:"如果对方先不尊重我，我不会给他好脸色。",reverse:true},
  { id:"bf_p21",dimension:"neuroticism",text:"在重要事件前我容易睡不好。",reverse:false},
  { id:"bf_p22",dimension:"neuroticism",text:"我经常会反复回想自己说错的话或做错的事。",reverse:false},
  { id:"bf_p23",dimension:"neuroticism",text:"外界变化很少会真正扰乱我的情绪。",reverse:true},
  { id:"bf_p24",dimension:"neuroticism",text:"当很多事情同时进行时我会感到焦虑。",reverse:false},
  { id:"bf_p25",dimension:"neuroticism",text:"我通常能迅速从失望中恢复过来。",reverse:true},
];

// ═══════════════════════════════════════════════════════
// 认知风格 — standard(24题) + pro(48题)
// ═══════════════════════════════════════════════════════
export const COGNITIVE_STYLE_STANDARD: QuizQuestion[] = [
  { id:"cs_s01",dimension:"abstractness",text:"看电影或读书时我常会去想它背后的主题和隐喻。",reverse:false},
  { id:"cs_s02",dimension:"abstractness",text:"把一个具体问题上升到更大的框架来理解是我的习惯。",reverse:false},
  { id:"cs_s03",dimension:"abstractness",text:"我觉得过于抽象的东西只是在浪费时间。",reverse:true},
  { id:"cs_s04",dimension:"abstractness",text:"我经常能从不同领域之间发现意想不到的联系。",reverse:false},
  { id:"cs_s05",dimension:"expression_structure",text:"写东西时我会很自然地组织段落结构。",reverse:false},
  { id:"cs_s06",dimension:"expression_structure",text:"别人经常说我说话条理清晰。",reverse:false},
  { id:"cs_s07",dimension:"expression_structure",text:"我发现口头表达时自己的思路容易跳跃。",reverse:true},
  { id:"cs_s08",dimension:"expression_structure",text:"我习惯在表达前先在脑子里搭好框架。",reverse:false},
  { id:"cs_s09",dimension:"cognitive_branching",text:"一个话题经常让我联想到好几个不相关的方向。",reverse:false},
  { id:"cs_s10",dimension:"cognitive_branching",text:"讨论中我经常会把话题带偏到另一个维度。",reverse:false},
  { id:"cs_s11",dimension:"cognitive_branching",text:"我更喜欢集中精力把一个想法彻底想透。",reverse:true},
  { id:"cs_s12",dimension:"cognitive_branching",text:"头脑风暴比按部就班地思考更让我兴奋。",reverse:false},
  { id:"cs_s13",dimension:"reflection_depth",text:"我经常会在事后重新审视自己的反应是否合适。",reverse:false},
  { id:"cs_s14",dimension:"reflection_depth",text:"了解自己为什么会有某种情绪对我来说很重要。",reverse:false},
  { id:"cs_s15",dimension:"reflection_depth",text:"我觉得过度自我分析有时候反而让人更纠结。",reverse:true},
  { id:"cs_s16",dimension:"reflection_depth",text:"朋友说我是一个比较了解自己的人。",reverse:false},
  { id:"cs_s17",dimension:"decision_latency",text:"面对多个好选项时我常常难以抉择。",reverse:false},
  { id:"cs_s18",dimension:"decision_latency",text:"我经常在做出决定后还在想另一个选项会不会更好。",reverse:false},
  { id:"cs_s19",dimension:"decision_latency",text:"我通常能依靠直觉快速做出判断。",reverse:true},
  { id:"cs_s20",dimension:"decision_latency",text:"信息不够时我宁愿推迟决定而不是匆忙定下来。",reverse:false},
  { id:"cs_s21",dimension:"language_density",text:"别人有时会说我说得太详细了。",reverse:false},
  { id:"cs_s22",dimension:"language_density",text:"我喜欢把一件事的来龙去脉讲清楚而不是只给结论。",reverse:false},
  { id:"cs_s23",dimension:"language_density",text:"我觉得很多时候一句话就能说清楚的事没必要展开。",reverse:true},
  { id:"cs_s24",dimension:"language_density",text:"我在表达前会先删掉冗余的部分让信息更紧凑。",reverse:true},
];

export const COGNITIVE_STYLE_PRO: QuizQuestion[] = [
  ...COGNITIVE_STYLE_STANDARD,
  { id:"cs_p01",dimension:"abstractness",text:"数学或逻辑中的美感会让我感到兴奋。",reverse:false},
  { id:"cs_p02",dimension:"abstractness",text:"我在解释复杂事物时喜欢用模型或图示。",reverse:false},
  { id:"cs_p03",dimension:"abstractness",text:"比起概念讨论我更喜欢能直接落地的方案。",reverse:true},
  { id:"cs_p04",dimension:"abstractness",text:"我经常能察觉到不同事件之间的深层模式。",reverse:false},
  { id:"cs_p05",dimension:"expression_structure",text:"我在会议或讨论中发言前通常会先列要点。",reverse:false},
  { id:"cs_p06",dimension:"expression_structure",text:"我的笔记或文档别人通常能直接看懂。",reverse:false},
  { id:"cs_p07",dimension:"expression_structure",text:"我有想法但写出来往往不如脑子里清楚。",reverse:true},
  { id:"cs_p08",dimension:"expression_structure",text:"给他人讲解复杂问题时我能保持逻辑清晰。",reverse:false},
  { id:"cs_p09",dimension:"cognitive_branching",text:"阅读时我经常因为联想到别的东西而走神。",reverse:false},
  { id:"cs_p10",dimension:"cognitive_branching",text:"我的浏览器经常同时开着很多个标签页。",reverse:false},
  { id:"cs_p11",dimension:"cognitive_branching",text:"在多任务之间切换会明显降低我的效率。",reverse:true},
  { id:"cs_p12",dimension:"cognitive_branching",text:"我喜欢把看起来不相关的事情联系在一起讨论。",reverse:false},
  { id:"cs_p13",dimension:"reflection_depth",text:"我经常记日记或做复盘笔记。",reverse:false},
  { id:"cs_p14",dimension:"reflection_depth",text:"别人给我反馈后我通常会用很长时间消化。",reverse:false},
  { id:"cs_p15",dimension:"reflection_depth",text:"比起反思过去我更愿意专注当下。",reverse:true},
  { id:"cs_p16",dimension:"reflection_depth",text:"我会试图从每次失败或挫折中找出规律。",reverse:false},
  { id:"cs_p17",dimension:"decision_latency",text:"我买东西时经常会反复比较。",reverse:false},
  { id:"cs_p18",dimension:"decision_latency",text:"面临重大决定时我通常会咨询多个人的意见。",reverse:false},
  { id:"cs_p19",dimension:"decision_latency",text:"即使在压力下我也能保持决策速度。",reverse:true},
  { id:"cs_p20",dimension:"decision_latency",text:"拖延决定有时候是因为我不想面对可能的后果。",reverse:false},
  { id:"cs_p21",dimension:"language_density",text:"我发消息经常是一大段而不是一两句话。",reverse:false},
  { id:"cs_p22",dimension:"language_density",text:"我觉得能用越少的话讲明白一件事越厉害。",reverse:true},
  { id:"cs_p23",dimension:"language_density",text:"说话太快时我事后常常想补充或纠正。",reverse:false},
  { id:"cs_p24",dimension:"language_density",text:"我习惯在关键时刻用最精炼的语言表达核心意思。",reverse:true},
];

// ═══════════════════════════════════════════════════════
// 社交边界 — standard(24题) + pro(48题)
// ═══════════════════════════════════════════════════════
export const SOCIAL_ATTACHMENT_STANDARD: QuizQuestion[] = [
  { id:"sa_s01",dimension:"closeness_need",text:"有一两个能深聊的朋友对我来说就够了。",reverse:false},
  { id:"sa_s02",dimension:"closeness_need",text:"长时间没有和人深度交流我会感到空洞。",reverse:false},
  { id:"sa_s03",dimension:"closeness_need",text:"我不太需要通过关系来确认自己的价值。",reverse:true},
  { id:"sa_s04",dimension:"closeness_need",text:"知道有人在需要时会出现这件事本身就很安心。",reverse:false},
  { id:"sa_s05",dimension:"boundary_strength",text:"我能在不伤害关系的前提下对别人说不。",reverse:false},
  { id:"sa_s06",dimension:"boundary_strength",text:"别人情绪不好时我不会觉得自己有责任去哄。",reverse:false},
  { id:"sa_s07",dimension:"boundary_strength",text:"我会因为怕对方不高兴而答应其实不想做的事。",reverse:true},
  { id:"sa_s08",dimension:"boundary_strength",text:"一旦我觉得越界了我会直接说出来。",reverse:false},
  { id:"sa_s09",dimension:"emotional_labor_tolerance",text:"听完朋友倾诉后我常常感到疲惫。",reverse:false},
  { id:"sa_s10",dimension:"emotional_labor_tolerance",text:"我愿意花时间帮亲近的人处理情绪。",reverse:false},
  { id:"sa_s11",dimension:"emotional_labor_tolerance",text:"我可以连续接住几个人的情绪而不觉得累。",reverse:true},
  { id:"sa_s12",dimension:"emotional_labor_tolerance",text:"关系里如果只有我在提供情绪支持我会想退。",reverse:false},
  { id:"sa_s13",dimension:"conflict_style",text:"发生矛盾后我通常是先开口沟通的那个人。",reverse:false},
  { id:"sa_s14",dimension:"conflict_style",text:"我会等对方先表达态度再决定自己要怎么反应。",reverse:true},
  { id:"sa_s15",dimension:"conflict_style",text:"我觉得冷战比吵架更让人难受。",reverse:false},
  { id:"sa_s16",dimension:"conflict_style",text:"为避免冲突我可以暂时放下自己的不满。",reverse:true},
  { id:"sa_s17",dimension:"trust_latency",text:"认识一个人后我需要较长时间才会真正敞开心扉。",reverse:false},
  { id:"sa_s18",dimension:"trust_latency",text:"曾经被辜负的经历让我在关系中更谨慎。",reverse:false},
  { id:"sa_s19",dimension:"trust_latency",text:"我通常很快就能判断一个人是否值得信任。",reverse:true},
  { id:"sa_s20",dimension:"trust_latency",text:"别人对我好时我会先观察是真的还是客套。",reverse:false},
  { id:"sa_s21",dimension:"withdrawal_tendency",text:"在让我不舒服的关系里我会选择保持距离。",reverse:false},
  { id:"sa_s22",dimension:"withdrawal_tendency",text:"当我觉得被误解时第一反应是想离开。",reverse:false},
  { id:"sa_s23",dimension:"withdrawal_tendency",text:"即使关系出现问题我也会努力挽回而不是放弃。",reverse:true},
  { id:"sa_s24",dimension:"withdrawal_tendency",text:"我很少因为一时的不快就切断一段关系。",reverse:true},
];

export const SOCIAL_ATTACHMENT_PRO: QuizQuestion[] = [
  ...SOCIAL_ATTACHMENT_STANDARD,
  { id:"sa_p01",dimension:"closeness_need",text:"我宁可只有少数深度的关系也不要很多表面的关系。",reverse:false},
  { id:"sa_p02",dimension:"closeness_need",text:"独处太久后我会主动找人联系。",reverse:false},
  { id:"sa_p03",dimension:"closeness_need",text:"我不太会主动维系和朋友的联系。",reverse:true},
  { id:"sa_p04",dimension:"closeness_need",text:"失落时有人静静地陪着比说一堆话更有用。",reverse:false},
  { id:"sa_p05",dimension:"boundary_strength",text:"朋友借钱不还这种事我不会让它发生第二次。",reverse:false},
  { id:"sa_p06",dimension:"boundary_strength",text:"帮人可以,但不能每次都让我兜底。",reverse:false},
  { id:"sa_p07",dimension:"boundary_strength",text:"拒绝别人的请求后我常常会有点内疚。",reverse:true},
  { id:"sa_p08",dimension:"boundary_strength",text:"我清楚在每段关系里自己的底线是什么。",reverse:false},
  { id:"sa_p09",dimension:"emotional_labor_tolerance",text:"成为朋友的情绪支柱已经让我在几段关系里感到透支。",reverse:false},
  { id:"sa_p10",dimension:"emotional_labor_tolerance",text:"我需要偶尔从关系中抽离出来给自己充电。",reverse:false},
  { id:"sa_p11",dimension:"emotional_labor_tolerance",text:"即使自己状态不好我也能很好地回应别人的情绪需求。",reverse:true},
  { id:"sa_p12",dimension:"emotional_labor_tolerance",text:"我擅长在不伤害对方的前提下表达自己的容量有限。",reverse:false},
  { id:"sa_p13",dimension:"conflict_style",text:"如果对方不先提,我可能会把不满一直压在心里。",reverse:true},
  { id:"sa_p14",dimension:"conflict_style",text:"我会在冲突中努力保持冷静和理性。",reverse:false},
  { id:"sa_p15",dimension:"conflict_style",text:"关系修复后我通常能真正放下不翻旧账。",reverse:false},
  { id:"sa_p16",dimension:"conflict_style",text:"有时候我会用沉默或冷淡表达不满而不是直接说出来。",reverse:true},
  { id:"sa_p17",dimension:"trust_latency",text:"别人要真正走进我的安全区需要经过几道门槛。",reverse:false},
  { id:"sa_p18",dimension:"trust_latency",text:"我对于太快就对我表现出强烈喜欢的人会保持距离。",reverse:false},
  { id:"sa_p19",dimension:"trust_latency",text:"我觉得大多数人是可以信任的。",reverse:true},
  { id:"sa_p20",dimension:"trust_latency",text:"我会用一些小测试来观察一个人是否靠谱。",reverse:false},
  { id:"sa_p21",dimension:"withdrawal_tendency",text:"一旦关系让我反复感到消耗我会直接退出。",reverse:false},
  { id:"sa_p22",dimension:"withdrawal_tendency",text:"我相信有些关系退一步反而对双方都好。",reverse:false},
  { id:"sa_p23",dimension:"withdrawal_tendency",text:"在关系里无论多难我都会坚持到最后一刻。",reverse:true},
  { id:"sa_p24",dimension:"withdrawal_tendency",text:"我不太会因为短暂的摩擦就想结束一段关系。",reverse:true},
];
